services:
  - type: web
    name: hotel-feedback
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel-feedback-db
          property: connectionString